resources:
  - ../../base

namespace: production

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
    target:
      kind: Deployment
      name: my-app

images:
  - name: nginx
    newTag: "1.27"
